package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.GradleBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    expectSteps {
        gradle {
            tasks = "hi"
            buildFile = "build.gradle"
            workingDir = "base/project"
            gradleWrapperPath = ".."
        }
    }
    steps {
        update<GradleBuildStep>(0) {
            dockerImage = "openjdk"
        }
    }
}
