package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    params {
        remove {
            password("token", "credentialsJSON:72682f1f-468c-4b1b-9f0e-b26753de06ec")
        }
        add {
            password("token2", "credentialsJSON:72682f1f-468c-4b1b-9f0e-b26753de06ec")
        }
    }
}
