package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'UseArtifacts'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("UseArtifacts")) {
    dependencies {
        expect(RelativeId("BuildWithArtifacts")) {
            artifacts {
                buildRule = lastSuccessful()
                artifactRules = "* => a"
            }
            artifacts {
                buildRule = lastSuccessful()
                artifactRules = "* => b"
            }
        }
        update(RelativeId("BuildWithArtifacts")) {
            artifacts {
                buildRule = lastSuccessful()
                artifactRules = "* => a"
            }
            artifacts {
                buildRule = tag("qwe")
                artifactRules = "* => qwe"
            }
        }

    }
}
