package Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2

import Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2.buildTypes.*
import Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2.vcsRoots.*
import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project

object Project : Project({
    id("Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2")
    parentId("Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu")
    name = "SubProject1 (1)"

    vcsRoot(Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2_HttpsGithubComTcqaReposKotlinSettingsRefsHeadsMaster)

    buildType(Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2_Build)
})
