package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HttpsGithubComTcqaReposMyProject'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HttpsGithubComTcqaReposMyProject")) {
    val expected = GitVcsRoot({
        id("HttpsGithubComTcqaReposMyProject")
        name = "https://github.com/tcqa-repos/MyProject"
        url = "https://github.com/tcqa-repos/MyProject"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = "+:*"
    }

}
