package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_1.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'myroot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("myroot")) {
    val expected = GitVcsRoot({
        id("myroot")
        name = "myroot"
        url = "https://github.com/tcqa-repos/myproject"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        url = "ssh://git@github.com/tcqa-repos/myproject"
        authMethod = uploadedKey {
            userName = ""
            uploadedKey = "ge.key"
            passphrase = ""
        }
    }

}
