package Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu.patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with uuid = '8fbf17f5-1746-4c31-8eea-7322573e8ca4' (id = 'Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2_HttpsGithubComTcqaReposKotlinSettingsRefsHeadsMaster')
in the project with id = 'Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2', and delete the patch script.
*/
create(AbsoluteId("Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2"), GitVcsRoot({
    uuid = "8fbf17f5-1746-4c31-8eea-7322573e8ca4"
    id("Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2_HttpsGithubComTcqaReposKotlinSettingsRefsHeadsMaster")
    name = "https://github.com/tcqa-repos/KotlinSettings"
    url = "https://github.com/tcqa-repos/KotlinSettings"
    branch = "refs/heads/TW-66783-2"
    authMethod = password {
        userName = "tcqa-repos"
        password = "credentialsJSON:f450f0e3-c536-4090-89d4-1928a49c4a6b"
    }
}))

