package Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu.patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2'
in the project with id = 'Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu', and delete the patch script.
*/
create(AbsoluteId("Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu"), Project({
    id("Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu_SubProject1_2")
    parentId("Issues_Tw66783LockingUiViaKotlinDslLockAlsoEnablingSynchronisationForAllSu")
    name = "SubProject1 (1)"
}))

